spring:
  application:
    name: activity-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/aiacticityfitness
      database: aiacticityfitness

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8082