spring:
  application:
    name: activity-service

  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}

server:
  port: 8082